name: Daily Email Reminder

on:
  schedule:
    - cron: "0 11 * * *"  # Runs at 6 PM Vietnam time (11 AM UTC)
  workflow_dispatch:  # Allows manual execution

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Reminder Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Daily Reminder: Don't Forget to Commit!"
          body: "This is your daily reminder to commit your work to GitHub! Stay consistent! 💪🔥"
          to: your-email@gmail.com
          from: GitHub Reminder Bot
